#!/bin/sh
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"  <<-EOSQL
    CREATE USER $DB_LOCAL_USER WITH PASSWORD '$DB_LOCAL_USER_PWD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $DB_LOCAL_USER;
    GRANT ALL ON SCHEMA public TO $DB_LOCAL_USER;
EOSQL